cipher: Fix SM3 avx/bmi2 compilation error
* cipher/sm3-avx-bmi2-amd64.S: Change K0-K63 macros to signed decimal.
--

There are a lot of the following errors compiling with GNU assembler
version 2.27-41:

  sm3-avx-bmi2-amd64.S: Assembler messages:
  sm3-avx-bmi2-amd64.S:402: Error: 0xf3988a32 out range of signed
    32bit displacement

The newer GNU assembler does not have this issue. It can be fixed by
changing K0-K63 macros from hex-format to signed decimal values.
Also remove unused macro 'addl3'.

Signed-off-by: Tianjia Zhang <tianjia.zhang@linux.alibaba.com>